name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aflasso/dotnet-api:latest

  run-container:

    runs-on: [self-hosted]
    needs: build-and-push

    steps:
    
    - name: Pull Docker image
      run: docker pull aflasso/dotnet-api
      
    - name: Stop and remove old container (if exists)
      run: |
          docker stop dotnet-api || true
          docker rm dotnet-api || true

    - name: Run new container with timestamp tag
      run: |
          docker run -dit --name dotnet-api -p 80:8080 aflasso/dotnet-api
